# BasketIQ — Step 5: Market Basket Analysis

**Goal of this notebook:** find products that are frequently bought **together** in the same order, using **association rule mining** (the Apriori algorithm).

This is the classic technique behind "customers who bought X also bought Y" recommendations, and behind decisions like which products to bundle, discount together, or place near each other in a store/website.

**Note:** a new library is needed for this step — `mlxtend` has been added to `requirements.txt`. Run `pip install -r requirements.txt` again before starting.

## 1. Import libraries and load the cleaned data

In [17]:
import pandas as pd
from pathlib import Path
from mlxtend.frequent_patterns import apriori, association_rules

pd.set_option('display.max_columns', None)

In [18]:
PROCESSED_DATA_PATH = Path('..') / 'data' / 'processed' / 'online_retail_clean.csv'

df = pd.read_csv(PROCESSED_DATA_PATH)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

## 2. Remove non-product line items

The dataset includes a few `Description` values that aren't real products — they're accounting/operational line items that happen to be recorded the same way as a product row (e.g. `POSTAGE` for shipping fees). If we leave these in, they show up in almost every invoice and pollute the results with meaningless "rules" like *"customers who buy X also pay for postage"* — true, but not useful, and it crowds out genuinely interesting product relationships.

We filter these out before building the basket.

In [19]:
# Known non-product entries in this dataset (shipping, fees, manual adjustments, etc.)
NON_PRODUCT_DESCRIPTIONS = [
    'POSTAGE',
    'DOTCOM POSTAGE',
    'CARRIAGE',
    'Manual',
    'BANK CHARGES',
    'AMAZON FEE',
    'SAMPLES',
    'ADJUST BAD DEBT',
]

rows_before = len(df)
df = df[~df['Description'].isin(NON_PRODUCT_DESCRIPTIONS)]
rows_after = len(df)

print(f'Removed {rows_before - rows_after} non-product rows ({rows_before} -> {rows_after})')

Removed 1527 non-product rows (392692 -> 391165)

## 3. Why we focus on a single country

Market basket analysis needs to build a huge table: **one row per invoice, one column per product**. With thousands of unique products and hundreds of thousands of invoices across every country mixed together, that table becomes extremely large and slow to process, and mixes shopping patterns from very different markets.

A standard approach (and the one we'll use here) is to run the analysis **per country**, starting with one market. We'll use **France**, a common and reasonably sized choice for this dataset, but you can change `COUNTRY` below to any market you're curious about.

In [20]:
# See which countries have enough transactions to make this analysis meaningful
df['Country'].value_counts().head(15)

Country
United Kingdom     348887
Germany              8643
France               8019
EIRE                 7126
Spain                2417
Netherlands          2322
Belgium              1935
Switzerland          1810
Portugal             1416
Australia            1180
Norway               1048
Channel Islands       743
Italy                 741
Finland               647
Cyprus                601
Name: count, dtype: int64

In [21]:
COUNTRY = 'France'  # <-- change this to analyze a different market

df_country = df[df['Country'] == COUNTRY]
print(f'Transactions for {COUNTRY}: {len(df_country)}')
print(f'Unique invoices: {df_country["InvoiceNo"].nunique()}')
print(f'Unique products: {df_country["Description"].nunique()}')

Transactions for France: 8019
Unique invoices: 379
Unique products: 1541

## 4. Build the "basket" matrix

We reshape the data so that:
- each **row** = one invoice (one shopping trip)
- each **column** = one product
- each **value** = how many units of that product were bought on that invoice (0 if not bought at all)

This is done with a pivot table.

In [22]:
basket = (
    df_country.groupby(['InvoiceNo', 'Description'])['Quantity']
    .sum()
    .unstack()          # turns the Description index level into columns
    .fillna(0)           # products not bought on an invoice become 0 instead of missing
)

print('Basket shape (invoices x products):', basket.shape)
basket.head()

Basket shape (invoices x products): (379, 1541)

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,15CM CHRISTMAS GLASS BALL 20 LIGHTS,16 PIECE CUTLERY SET PANTRY DESIGN,18PC WOODEN CUTLERY SET DISPOSABLE,20 DOLLY PEGS RETROSPOT,200 RED + WHITE BENDY STRAWS,3 HOOK HANGER MAGIC GARDEN,3 PIECE SPACEBOY COOKIE CUTTER SET,3 RAFFIA RIBBONS 50'S CHRISTMAS,3 STRIPEY MICE FELTCRAFT,3 TIER CAKE TIN RED AND CREAM,3 TRADITIONAl BISCUIT CUTTERS SET,36 DOILIES DOLLY GIRL,36 DOILIES VINTAGE CHRISTMAS,36 FOIL HEART CAKE CASES,36 FOIL STAR CAKE CASES,36 PENCILS TUBE RED RETROSPOT,36 PENCILS TUBE SKULLS,36 PENCILS TUBE WOODLAND,3D HEARTS HONEYCOMB PAPER GARLAND,3D TRADITIONAL CHRISTMAS STICKERS,3D VINTAGE CHRISTMAS STICKERS,4 IVORY DINNER CANDLES SILVER FLOCK,4 PINK DINNER CANDLE SILVER FLOCK,4 TRADITIONAL SPINNING TOPS,5 HOOK HANGER MAGIC TOADSTOOL,5 HOOK HANGER RED MAGIC TOADSTOOL,6 GIFT TAGS 50'S CHRISTMAS,6 GIFT TAGS VINTAGE CHRISTMAS,6 RIBBONS EMPIRE,6 RIBBONS RUSTIC CHARM,6 ROCKET BALLOONS,60 CAKE CASES DOLLY GIRL DESIGN,60 CAKE CASES VINTAGE CHRISTMAS,60 TEATIME FAIRY CAKE CASES,6PC WOOD PLATE SET DISPOSABLE,72 SWEETHEART FAIRY CAKE CASES,A PRETTY THANK YOU CARD,ABC TREASURE BOOK BOX,ADULT APRON APPLE DELIGHT,ADVENT CALENDAR GINGHAM SACK,AGED GLASS SILVER T-LIGHT HOLDER,AIRLINE BAG VINTAGE JET SET BROWN,AIRLINE BAG VINTAGE JET SET RED,AIRLINE BAG VINTAGE JET SET WHITE,AIRLINE BAG VINTAGE TOKYO 78,AIRLINE BAG VINTAGE WORLD CHAMPION,"AIRLINE LOUNGE,METAL SIGN",ALARM CLOCK BAKELIKE CHOCOLATE,ALARM CLOCK BAKELIKE GREEN,ALARM CLOCK BAKELIKE IVORY,ALARM CLOCK BAKELIKE ORANGE,ALARM CLOCK BAKELIKE PINK,ALARM CLOCK BAKELIKE RED,ALPHABET HEARTS STICKER SHEET,ALUMINIUM STAMPED HEART,AMETHYST CHUNKY BEAD BRACELET W STR,ANGEL DECORATION STARS ON DRESS,ANTIQUE ALL GLASS CANDLESTICK,ANTIQUE GLASS DRESSING TABLE POT,ANTIQUE GLASS PEDESTAL BOWL,ANTIQUE SILVER BAUBLE LAMP,ANTIQUE SILVER T-LIGHT GLASS,ANTIQUE SILVER TEA GLASS ENGRAVED,APPLE BATH SPONGE,AREA PATROLLED METAL SIGN,ASS COLOUR GLOWING TIARAS,ASS FLORAL PRINT MULTI SCREWDRIVER,ASSORTED BOTTLE TOP MAGNETS,ASSORTED COLOUR BIRD ORNAMENT,ASSORTED COLOUR MINI CASES,ASSORTED COLOUR T-LIGHT HOLDER,ASSORTED COLOURS SILK FAN,ASSORTED EASTER DECORATIONS BELLS,ASSORTED EASTER GIFT TAGS,"ASSORTED FLOWER COLOUR ""LEIS""",ASSORTED TUTTI FRUTTI BRACELET,ASSORTED TUTTI FRUTTI MIRROR,ASSORTED TUTTI FRUTTI SMALL PURSE,ASSTD DESIGN 3D PAPER STICKERS,ASSTD DESIGN RACING CAR PEN,ASSTD FRUIT+FLOWERS FRIDGE MAGNETS,ASSTD RASTA KEY-CHAINS,BABUSHKA LIGHTS STRING OF 10,BAG 125g SWIRLY MARBLES,BAG 250g SWIRLY MARBLES,BAKING MOULD CHOCOLATE CUPCAKES,BAKING MOULD EASTER EGG MILK CHOC,BAKING MOULD EASTER EGG WHITE CHOC,BAKING MOULD HEART MILK CHOCOLATE,BAKING MOULD HEART WHITE CHOCOLATE,BAKING SET 9 PIECE RETROSPOT,BAKING SET SPACEBOY DESIGN,BALLOON ART MAKE YOUR OWN FLOWERS,BALLOON PUMP WITH 10 BALLOONS,BALLOON WATER BOMB PACK OF 35,BALLOONS WRITING SET,BANQUET BIRTHDAY CARD,BASKET OF TOADSTOOLS,BATH BUILDING BLOCK WORD,BEADED CRYSTAL HEART BLUE LARGE,BELLE JARDINIERE CUSHION COVER,BEWARE OF THE CAT METAL SIGN,BIG DOUGHNUT FRIDGE MAGNETS,BILI NUT AND WOOD NECKLACE,BINGO SET,BIRD DECORATION GREEN POLKADOT,BIRD DECORATION RED RETROSPOT,BIRD HOUSE HOT WATER BOTTLE,BIRDS MOBILE VINTAGE DESIGN,"BIRTHDAY CARD, RETRO SPOT",BISCUIT TIN 50'S CHRISTMAS,BISCUIT TIN VINTAGE CHRISTMAS,BISCUIT TIN VINTAGE GREEN,BISCUIT TIN VINTAGE RED,BLACK AND WHITE CAT BOWL,BLACK CANDELABRA T-LIGHT HOLDER,BLACK CHRISTMAS TREE 120CM,BLACK CHUNKY BEAD BRACELET W STRAP,BLACK ENAMEL FLOWER RING,BLACK KITCHEN SCALES,BLACK LOVE BIRD CANDLE,BLACK PIRATE TREASURE CHEST,BLACK RECORD COVER FRAME,BLACK/BLUE POLKADOT UMBRELLA,BLUE 3 PIECE POLKADOT CUTLERY SET,BLUE COAT RACK PARIS FASHION,BLUE DINER WALL CLOCK,BLUE DRAWER KNOB ACRYLIC EDWARDIAN,BLUE EGG SPOON,BLUE FLY SWAT,BLUE GEISHA GIRL,BLUE HAPPY BIRTHDAY BUNTING,BLUE HARMONICA IN BOX,BLUE OWL SOFT TOY,BLUE PAISLEY JOURNAL,BLUE PARTY BAGS,BLUE POLKADOT BEAKER,BLUE POLKADOT BOWL,BLUE POLKADOT COFFEE MUG,BLUE POLKADOT CUP,BLUE POLKADOT GARDEN PARASOL,BLUE POLKADOT KIDS BAG,BLUE POLKADOT PASSPORT COVER,BLUE POLKADOT PLATE,BLUE POLKADOT WRAP,BLUE REFECTORY CLOCK,BLUE ROSE FABRIC MIRROR,BLUE SCANDINAVIAN PAISLEY WRAP,BLUE SCOTTIE DOG W FLOWER PATTERN,BLUE STRIPE CERAMIC DRAWER KNOB,BLUE TEA TOWEL CLASSIC DESIGN,BLUE VINTAGE SPOT BEAKER,BOOM BOX SPEAKER BOYS,BOOM BOX SPEAKER GIRLS,BOTANICAL GARDENS WALL CLOCK,BOTANICAL LILY GREETING CARD,BOTTLE BAG RETROSPOT,BOX OF 24 COCKTAIL PARASOLS,BOX OF 6 CHRISTMAS CAKE DECORATIONS,BOX OF 6 MINI 50'S CRACKERS,BOX OF 6 MINI VINTAGE CRACKERS,BOX OF VINTAGE ALPHABET BLOCKS,BOX OF VINTAGE JIGSAW BLOCKS,BOYS VINTAGE TIN SEASIDE BUCKET,BREAD BIN DINER STYLE IVORY,BREAD BIN DINER STYLE PINK,BREAD BIN DINER STYLE RED,BRIGHT BLUES RIBBONS,BROCANTE SHELF WITH HOOKS,BROWN CHECK CAT DOORSTOP,BROWN KUKUI COCONUT SEED NECKLACE,BUFFALO BILL TREASURE BOOK BOX,BULL DOG BOTTLE TOP WALL CLOCK,BUNDLE OF 3 ALPHABET EXERCISE BOOKS,BUNDLE OF 3 RETRO NOTE BOOKS,BUNDLE OF 3 SCHOOL EXERCISE BOOKS,BUNNY WOODEN PAINTED WITH BIRD,BUTTERFLIES STICKERS,CABIN BAG VINTAGE RETROSPOT,CACTI T-LIGHT CANDLES,CAKE PLATE LOVEBIRD PINK,CAKE PLATE LOVEBIRD WHITE,CAKE STAND 3 TIER MAGIC GARDEN,CAKE STAND LOVEBIRD 2 TIER PINK,CAKE STAND WHITE TWO TIER LACE,CAKES AND BOWS GIFT TAPE,CAKES AND RABBITS DESIGN FLANNEL,CALENDAR PAPER CUT DESIGN,CAMOUFLAGE LED TORCH,CANDY SHOP STICKER SHEET,CANDY SPOT HAND BAG,CARAVAN SQUARE TISSUE BOX,CARD BILLBOARD FONT,CARD BIRTHDAY COWBOY,CARD CAT AND TREE,CARD CHRISTMAS VILLAGE,CARD CIRCUS PARADE,CARD DOLLY GIRL,CARD GINGHAM ROSE,CARD HOLDER GINGHAM HEART,CARD HOLDER LOVE BIRD SMALL,CARD I LOVE LONDON,CARD MOTORBIKE SANTA,CARD PARTY GAMES,CARD PSYCHEDELIC APPLES,CARD SUKI BIRTHDAY,CARD WEDDING DAY,CARDHOLDER GINGHAM CHRISTMAS TREE,CAROUSEL DESIGN WASHBAG,CARROT CHARLIE+LOLA COASTER SET,CARTOON PENCIL SHARPENERS,CAST IRON HOOK GARDEN TROWEL,CAT BOWL VINTAGE CREAM,CERAMIC BOWL WITH STRAWBERRY DESIGN,CERAMIC CHERRY CAKE MONEY BANK,CERAMIC HEART FAIRY CAKE MONEY BANK,CERAMIC PIRATE CHEST MONEY BANK,CERAMIC STRAWBERRY CAKE MONEY BANK,CERAMIC STRAWBERRY DESIGN MUG,CERAMIC STRAWBERRY MONEY BOX,CERAMIC STRAWBERRY TRINKET TRAY,CHARLIE & LOLA WASTEPAPER BIN FLORA,CHARLOTTE BAG APPLES DESIGN,CHARLOTTE BAG DOLLY GIRL DESIGN,CHARLOTTE BAG PINK POLKADOT,CHARLOTTE BAG SUKI DESIGN,CHARLOTTE BAG VINTAGE ALPHABET,CHERRY BLOSSOM DECORATIVE FLASK,CHERRY BLOSSOM DECORATIVE FLASK,CHERRY CROCHET FOOD COVER,CHERUB HEART DECORATION GOLD,CHEST OF DRAWERS GINGHAM HEART,CHICK GREY HOT WATER BOTTLE,CHILDREN'S APRON DOLLY GIRL,CHILDREN'S CIRCUS PARADE MUG,CHILDREN'S SPACEBOY MUG,CHILDRENS APRON APPLES DESIGN,CHILDRENS APRON SPACEBOY DESIGN,CHILDRENS CUTLERY CIRCUS PARADE,CHILDRENS CUTLERY DOLLY GIRL,CHILDRENS CUTLERY POLKADOT BLUE,CHILDRENS CUTLERY POLKADOT GREEN,CHILDRENS CUTLERY POLKADOT PINK,CHILDRENS CUTLERY RETROSPOT RED,CHILDRENS CUTLERY SPACEBOY,CHILDRENS DOLLY GIRL MUG,CHILDRENS GARDEN GLOVES BLUE,CHILDRENS GARDEN GLOVES PINK,CHILDRENS TOY COOKING UTENSIL SET,CHILDS BREAKFAST SET CIRCUS PARADE,CHILDS BREAKFAST SET DOLLY GIRL,CHILDS BREAKFAST SET SPACEBOY,CHILDS GARDEN BRUSH BLUE,CHILDS GARDEN BRUSH PINK,CHILDS GARDEN FORK BLUE,CHILDS GARDEN FORK PINK,CHILDS GARDEN RAKE BLUE,CHILDS GARDEN RAKE PINK,CHILDS GARDEN SPADE BLUE,CHILDS GARDEN SPADE PINK,CHILDS GARDEN TROWEL BLUE,CHILDS GARDEN TROWEL PINK,CHINESE DRAGON PAPER LANTERNS,CHOCOLATE BOX RIBBONS,CHOCOLATE CALCULATOR,CHOCOLATE HOT WATER BOTTLE,CHOCOLATE THIS WAY METAL SIGN,CHRISTMAS CARD SCREEN PRINT,CHRISTMAS CARD STACK OF PRESENTS,CHRISTMAS CRAFT LITTLE FRIENDS,CHRISTMAS CRAFT TREE TOP ANGEL,CHRISTMAS CRAFT WHITE FAIRY,CHRISTMAS GINGHAM STAR,CHRISTMAS GINGHAM TREE,CHRISTMAS HANGING SNOWFLAKE,CHRISTMAS LIGHTS 10 REINDEER,CHRISTMAS LIGHTS 10 SANTAS,CHRISTMAS LIGHTS 10 VINTAGE BAUBLES,CHRISTMAS METAL POSTCARD WITH BELLS,CHRISTMAS METAL TAGS ASSORTED,CHRISTMAS PUDDING TRINKET POT,CHRISTMAS RETROSPOT ANGEL WOOD,CHRISTMAS RETROSPOT TREE WOOD,CHRISTMAS STAR WISH LIST CHALKBOARD,CHRISTMAS TOILET ROLL,CHRISTMAS TREE HANGING GOLD,CHRISTMAS TREE PAINTED ZINC,CHRYSANTHEMUM NOTEBOOK,CINAMMON & ORANGE WREATH,CINNAMON SCENTED VOTIVE CANDLE,CIRCUS PARADE BABY GIFT SET,CIRCUS PARADE CHILDRENS EGG CUP,CIRCUS PARADE LUNCH BOX,CLASSIC CAFE SUGAR DISPENSER,CLASSIC CHROME BICYCLE BELL,CLASSIC GLASS COOKIE JAR,CLASSIC METAL BIRDCAGE PLANT HOLDER,CLASSICAL ROSE SMALL VASE,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,CLOTHES PEGS RETROSPOT PACK 24,COCKTAIL SWORDS 50 PIECES,COFFEE MUG APPLES DESIGN,COFFEE MUG CAT + BIRD DESIGN,COFFEE MUG DOG + BALL DESIGN,COFFEE MUG PEARS DESIGN,COFFEE MUG PINK PAISLEY DESIGN,COLOURING PENCILS BROWN TUBE,COOK WITH WINE METAL SIGN,CORDIAL GLASS JUG,COSY HOUR CIGAR BOX MATCHES,COSY SLIPPER SHOES SMALL GREEN,COTTON APRON PANTRY DESIGN,COWBOYS AND INDIANS BIRTHDAY CARD,CREAM FELT EASTER EGG BASKET,CREAM HEART CARD HOLDER,CREAM SWEETHEART EGG HOLDER,CREAM SWEETHEART MINI CHEST,CROCHET ROSE PURSE WITH SUEDE BACK,CUPCAKE LACE PAPER SET 6,CURIOUS IMAGES GIFT WRAP SET,CUTE CATS TAPE,DAIRY MAID STRIPE MUG,DAIRY MAID TRADITIONAL TEAPOT,DAISIES HONEYCOMB GARLAND,DANISH ROSE DECORATIVE PLATE,DANISH ROSE DELUXE COASTER,DANISH ROSE ROUND SEWING BOX,DANISH ROSE TRINKET TRAYS,DECORATIVE CATS BATHROOM BOTTLE,DECORATIVE WICKER HEART LARGE,DELUXE SEWING KIT,DINOSAUR HEIGHT CHART STICKER SET,DINOSAUR KEYRINGS ASSORTED,DINOSAUR LUNCH BOX WITH CUTLERY,DINOSAUR PARTY BAG + STICKER SET,DINOSAURS WRITING SET,DISCO BALL CHRISTMAS DECORATION,DO NOT TOUCH MY STUFF DOOR HANGER,DOCTOR'S BAG SOFT TOY,DOG BOWL CHASING BALL DESIGN,DOG BOWL VINTAGE CREAM,DOGGY RUBBER,DOILEY STORAGE TIN,DOILY THANK YOU CARD,DOLLY GIRL BABY GIFT SET,DOLLY GIRL CHILDRENS BOWL,DOLLY GIRL CHILDRENS CUP,DOLLY GIRL CHILDRENS EGG CUP,DOLLY GIRL LUNCH BOX,DOLLY GIRL MINI BACKPACK,DOLLY HONEYCOMB GARLAND,DOLLY MIXTURE CHILDREN'S UMBRELLA,DOOR HANGER MUM + DADS ROOM,DOORMAT 3 SMILEY CATS,DOORMAT AIRMAIL,DOORMAT BLACK FLOCK,DOORMAT ENGLISH ROSE,DOORMAT FAIRY CAKE,DOORMAT FANCY FONT HOME SWEET HOME,DOORMAT HEARTS,DOORMAT HOME SWEET HOME BLUE,DOORMAT I LOVE LONDON,DOORMAT KEEP CALM AND COME IN,DOORMAT MERRY CHRISTMAS RED,DOORMAT NEIGHBOURHOOD WITCH,DOORMAT NEW ENGLAND,DOORMAT PEACE ON EARTH BLUE,DOORMAT RED RETROSPOT,DOORMAT RESPECTABLE HOUSE,DOORMAT SPOTTY HOME SWEET HOME,DOORMAT UNION FLAG,DOORMAT UNION JACK GUNS AND ROSES,DOORMAT VINTAGE LEAF,DOORMAT WELCOME TO OUR HOME,DOORSTOP RETROSPOT HEART,DOUGHNUT LIP GLOSS,DRAWER KNOB CERAMIC IVORY,DRAWER KNOB CERAMIC RED,DRAWER KNOB CRACKLE GLAZE BLUE,DRAWER KNOB CRACKLE GLAZE GREEN,DRAWER KNOB CRACKLE GLAZE PINK,DRAWER KNOB VINTAGE GLASS BALL,DRAWER KNOB VINTAGE GLASS HEXAGON,DRAWER KNOB VINTAGE GLASS STAR,EASTER TIN BUNNY BOUQUET,EASTER TIN CHICKS IN GARDEN,EASTER TIN CHICKS PINK DAISY,EASTER TIN KEEPSAKE,EDWARDIAN PARASOL BLACK,EDWARDIAN PARASOL NATURAL,EDWARDIAN PARASOL PINK,EDWARDIAN PARASOL RED,EGG CUP MILKMAID HEIDI,EGG CUP MILKMAID HELGA,EGG CUP MILKMAID INGRID,EGG CUP NATURAL CHICKEN,EGG FRYING PAN RED,EIGHT PIECE SNAKE SET,"ELEPHANT, BIRTHDAY CARD,",EMBROIDERED RIBBON REEL DAISY,EMBROIDERED RIBBON REEL EMILY,EMBROIDERED RIBBON REEL REBECCA,EMBROIDERED RIBBON REEL ROSIE,EMBROIDERED RIBBON REEL SALLY,EMBROIDERED RIBBON REEL SUSIE,EMPIRE BIRTHDAY CARD,EMPIRE TISSUE BOX,ENAMEL BLUE RIM COFFEE CONTAINER,ENAMEL COLANDER CREAM,ENAMEL FLOWER JUG CREAM,ENAMEL PINK COFFEE CONTAINER,ENAMEL PINK TEA CONTAINER,ENCHANTED BIRD COATHANGER 5 HOOK,ENGLISH ROSE GARDEN SECATEURS,ENGLISH ROSE HOT WATER BOTTLE,ENGLISH ROSE NOTEBOOK A7 SIZE,ENGLISH ROSE SMALL SCENTED FLOWER,ETCHED GLASS COASTER,FAIRY CAKE BIRTHDAY CANDLE SET,FAIRY CAKE FLANNEL ASSORTED COLOUR,FAIRY CAKES NOTEBOOK A6 SIZE,FAIRY CAKES NOTEBOOK A7 SIZE,FAIRY TALE COTTAGE NIGHT LIGHT,FAIRY TALE COTTAGE NIGHTLIGHT,FAMILY PHOTO FRAME CORNICE,"FANCY FONT BIRTHDAY CARD,",FANCY FONTS BIRTHDAY WRAP,FAWN BLUE HOT WATER BOTTLE,"FEATHER PEN,LIGHT PINK",FELT EGG COSY CHICKEN,FELT FARM ANIMAL WHITE BUNNY,FELT TOADSTOOL SMALL,FELT TOADSTOOL LARGE,FELTCRAFT 6 FLOWER FRIENDS,FELTCRAFT BOY JEAN-PAUL KIT,FELTCRAFT CHRISTMAS FAIRY,FELTCRAFT CUSHION BUTTERFLY,FELTCRAFT CUSHION OWL,FELTCRAFT CUSHION RABBIT,FELTCRAFT DOLL EMILY,FELTCRAFT DOLL MARIA,FELTCRAFT DOLL MOLLY,FELTCRAFT DOLL ROSIE,FELTCRAFT GIRL AMELIE KIT,FELTCRAFT HAIRBAND PINK AND BLUE,FELTCRAFT HAIRBANDS PINK AND WHITE,FELTCRAFT PRINCESS CHARLOTTE DOLL,FELTCRAFT PRINCESS LOLA DOLL,FELTCRAFT PRINCESS OLIVIA DOLL,FIRST CLASS PASSPORT COVER,FIVE HEART HANGING DECORATION,FLOWER VINE RAFFIA FOOD COVER,FLOWERS TILE HOOK,FLUTED ANTIQUE CANDLE HOLDER,FLYING PIG WATERING CAN,FOLDING BUTTERFLY MIRROR HOT PINK,FOLDING BUTTERFLY MIRROR IVORY,FOLDING BUTTERFLY MIRROR RED,FOLDING UMBRELLA BLACKBLUE POLKADOT,FOLDING UMBRELLA CHOCOLATE POLKADOT,FOLDING UMBRELLA CREAM POLKADOT,FOLDING UMBRELLA PINKWHITE POLKADOT,FOLDING UMBRELLA RED/WHITE POLKADOT,FOLDING UMBRELLA WHITE/RED POLKADOT,FOLKART STAR CHRISTMAS DECORATIONS,FOOD CONTAINER SET 3 LOVE HEART,FOOD/DRINK SPONGE STICKERS,FOOT STOOL HOME SWEET HOME,FRENCH ENAMEL CANDLEHOLDER,FRENCH ENAMEL WATER BASIN,FRENCH STYLE STORAGE JAR BONBONS,FRIDGE MAGNETS LA VIE EN ROSE,FRIDGE MAGNETS LES ENFANTS ASSORTED,FRIDGE MAGNETS US DINER ASSORTED,FRYING PAN PINK POLKADOT,FRYING PAN RED RETROSPOT,FRYING PAN UNION FLAG,FULL ENGLISH BREAKFAST PLATE,FUNKY DIVA PEN,FUNKY WASHING UP GLOVES ASSORTED,GARDENERS KNEELING PAD CUP OF TEA,GARDENERS KNEELING PAD KEEP CALM,GARLAND WITH HEARTS AND BELLS,GARLAND WITH STARS AND BELLS,GIANT 50'S CHRISTMAS CRACKER,GIFT BAG BIRTHDAY,GIFT BAG PSYCHEDELIC APPLES,GIN & TONIC DIET GREETING CARD,GIN + TONIC DIET METAL SIGN,GINGERBREAD MAN COOKIE CUTTER,GINGHAM HEART DOORSTOP RED,GINGHAM HEART DECORATION,GINGHAM RECIPE BOOK BOX,GIRAFFE WOODEN RULER,GIRLS VINTAGE TIN SEASIDE BUCKET,GLAMOROUS MUG,GLASS BEURRE DISH,GLASS SONGBIRD STORAGE JAR,GLASS BONNE JAM JAR,GLASS CLOCHE SMALL,GLASS JAR DAISY FRESH COTTON WOOL,GLASS JAR PEACOCK BATH SALTS,GLITTER CHRISTMAS STAR,GLITTER HEART DECORATION,GLITTER STAR GARLAND WITH BELLS,GRAND CHOCOLATECANDLE,GREEN 3 PIECE POLKADOT CUTLERY SET,GREEN BIRDHOUSE DECORATION,GREEN CHRISTMAS TREE STRING 20LIGHT,GREEN GEISHA GIRL,GREEN GIANT GARDEN THERMOMETER,GREEN METAL BOX ARMY SUPPLIES,GREEN POLKADOT BOWL,GREEN POLKADOT PLATE,GREEN REGENCY TEACUP AND SAUCER,GREEN VINTAGE SPOT BEAKER,"GREETING CARD, OVERCROWDED POOL.",GREY FLORAL FELTCRAFT SHOULDER BAG,GREY HEART HOT WATER BOTTLE,GROW A FLYTRAP OR SUNFLOWER IN TIN,GROW YOUR OWN HERBS SET OF 3,GROW YOUR OWN PLANT IN A CAN,GUMBALL COAT RACK,GUMBALL MAGAZINE RACK,GYMKHANA TREASURE BOOK BOX,HAIRCLIPS FORTIES FABRIC ASSORTED,HAND WARMER BABUSHKA DESIGN,HAND WARMER BIRD DESIGN,HAND WARMER RED LOVE HEART,HAND WARMER RED RETROSPOT,HAND WARMER SCOTTY DOG DESIGN,HAND WARMER UNION JACK,HANGING BUTTERFLY T-LIGHT HOLDER,HANGING HEART BONHEUR,HANGING HEART JAR T-LIGHT HOLDER,HANGING HEART ZINC T-LIGHT HOLDER,HANGING HEN ON NEST DECORATION,HANGING MINI COLOURED BOTTLES,HANGING QUILTED PATCHWORK APPLES,HANGING SPRING FLOWER EGG SMALL,HAPPY STENCIL CRAFT,HEADS AND TAILS SPORTING FUN,HEART FILIGREE DOVE SMALL,HEART FILIGREE DOVE LARGE,HEART MINI PORTRAIT FRAME,HEART OF WICKER SMALL,HEART SHAPED HOLLY WREATH,HEART T-LIGHT HOLDER WILLIE WINKIE,HEART WOODEN CHRISTMAS DECORATION,HEART WREATH DECORATION WITH BELL,HEARTS STICKERS,HEN HOUSE W CHICK STANDING,HENRIETTA HEN MUG,HI TEC ALPINE HAND WARMER,HOLIDAY FUN LUDO,HOME BUILDING BLOCK WORD,HOME SWEET HOME CUSHION COVER,HOME SWEET HOME HOOK,HOME SWEET HOME METAL SIGN,HOME SWEET HOME MUG,HOMEMADE JAM SCENTED CANDLES,HOT BATHS METAL SIGN,HOT WATER BOTTLE BABUSHKA,HOT WATER BOTTLE KEEP CALM,HOT WATER BOTTLE TEA AND SYMPATHY,HOUSE SHAPE PENCIL SHARPENER,HYACINTH BULB T-LIGHT CANDLES,I LOVE LONDON BABY GIFT SET,I LOVE LONDON BEAKER,I'M ON HOLIDAY METAL SIGN,ICE CREAM BUBBLES,ICE CREAM DESIGN GARDEN PARASOL,ICE CREAM PEN LIP GLOSS,ICE CREAM SUNDAE LIP GLOSS,ICON MUG REVOLUTIONARY,ILLUSTRATED CAT BOWL,INFLATABLE POLITICAL GLOBE,IVORY DINER WALL CLOCK,IVORY GIANT GARDEN THERMOMETER,IVORY HANGING DECORATION HEART,IVORY KITCHEN SCALES,IVORY PILLAR CANDLE GOLD FLOCK,IVORY PILLAR CANDLE SILVER FLOCK,IVORY WICKER HEART LARGE,IVORY WICKER HEART MEDIUM,IVORY WICKER HEART SMALL,JAM CLOCK MAGNET,JAM JAR WITH GREEN LID,JAM JAR WITH PINK LID,JAM MAKING SET PRINTED,JAM MAKING SET WITH JARS,JAZZ HEARTS ADDRESS BOOK,JAZZ HEARTS PURSE NOTEBOOK,JIGSAW TOADSTOOLS 3 PIECE,JIGSAW TREE WITH BIRDHOUSE,JINGLE BELL HEART ANTIQUE GOLD,JINGLE BELL HEART DECORATION,JOY WOODEN BLOCK LETTERS,JUMBO BAG BAROQUE BLACK WHITE,JUMBO BAG 50'S CHRISTMAS,JUMBO BAG ALPHABET,JUMBO BAG APPLES,JUMBO BAG DOILEY PATTERNS,JUMBO BAG DOLLY GIRL DESIGN,JUMBO BAG OWLS,JUMBO BAG PEARS,JUMBO BAG PINK POLKADOT,JUMBO BAG PINK VINTAGE PAISLEY,JUMBO BAG RED RETROSPOT,JUMBO BAG SCANDINAVIAN BLUE PAISLEY,JUMBO BAG SPACEBOY DESIGN,JUMBO BAG STRAWBERRY,JUMBO BAG TOYS,JUMBO BAG VINTAGE CHRISTMAS,JUMBO BAG VINTAGE DOILY,JUMBO BAG VINTAGE LEAF,JUMBO BAG WOODLAND ANIMALS,JUMBO SHOPPER VINTAGE RED PAISLEY,JUMBO STORAGE BAG SKULLS,JUMBO STORAGE BAG SUKI,JUNGLE POPSICLES ICE LOLLY HOLDERS,JUNGLE POPSICLES ICE LOLLY MOULDS,KEEP OUT BOYS DOOR HANGER,"KEY FOB , BACK DOOR","KEY FOB , SHED",KEY RING BASEBALL BOOT ASSORTED,KEY RING BASEBALL BOOT UNION JACK,KINGS CHOICE BISCUIT TIN,KINGS CHOICE MUG,KINGS CHOICE TEA CADDY,KITTY PENCIL ERASERS,KNICKERBOCKERGLORY MAGNET ASSORTED,KNITTED UNION FLAG HOT WATER BOTTLE,LA JARDIN BOTANIQUE CUSHION COVER,LA PALMIERA TILE HOOK,LADIES & GENTLEMEN METAL SIGN,LADYBIRD + BEE RAFFIA FOOD COVER,LANDMARK FRAME COVENT GARDEN,LANDMARK FRAME NOTTING HILL,LANDMARK FRAME OXFORD STREET,LANTERN CREAM GAZEBO,LARGE BONNE JAM JAR T-LIGHT HOLDER,LARGE CAKE TOWEL PINK SPOTS,LARGE CAMPHOR WOOD FIELD MUSHROOM,LARGE DECO JEWELLERY STAND,LARGE HANGING IVORY & RED WOOD BIRD,LARGE HEART MEASURING SPOONS,LARGE IVORY HEART WALL ORGANISER,LARGE POPCORN HOLDER,LARGE PURPLE BABUSHKA NOTEBOOK,LARGE RED BABUSHKA NOTEBOOK,LARGE RED RETROSPOT WINDMILL,LARGE WHITE HEART OF WICKER,LARGE YELLOW BABUSHKA NOTEBOOK,LAUREL HEART ANTIQUE GOLD,LAUREL STAR ANTIQUE SILVER,LAVENDER SCENTED FABRIC HEART,LE JARDIN BOTANIQUE CUSHION COVER,LED TEA LIGHTS,LETS GO SHOPPING COTTON TOTE BAG,LIPSTICK PEN RED,LOLITA DESIGN COTTON TOTE BAG,LONDON BUS COFFEE MUG,LOVE BUILDING BLOCK WORD,LOVE GARLAND PAINTED ZINC,LOVE HEART SOCK HANGER,LOVE HOT WATER BOTTLE,LOVE LARGE WOOD LETTERS,LOVEBIRD HANGING DECORATION WHITE,LOVELY BONBON STICKER SHEET,LUNCH BAG BLACK SKULL.,LUNCH BAG ALPHABET DESIGN,LUNCH BAG APPLE DESIGN,LUNCH BAG CARS BLUE,LUNCH BAG DOILEY PATTERN,LUNCH BAG DOLLY GIRL DESIGN,LUNCH BAG PAISLEY PARK,LUNCH BAG PINK POLKADOT,LUNCH BAG RED RETROSPOT,LUNCH BAG RED VINTAGE DOILY,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG VINTAGE DOILY,LUNCH BAG VINTAGE LEAF DESIGN,LUNCH BAG WOODLAND,LUNCH BOX I LOVE LONDON,LUNCH BOX WITH CUTLERY RETROSPOT,MAGIC DRAWING SLATE BUNNIES,MAGIC DRAWING SLATE CIRCUS PARADE,MAGIC DRAWING SLATE DINOSAUR,MAGIC DRAWING SLATE DOLLY GIRL,MAGIC DRAWING SLATE GO TO THE FAIR,MAGIC DRAWING SLATE LEAP FROG,MAGIC DRAWING SLATE SPACEBOY,MAGIC SHEEP WOOL GROWING FROM PAPER,MAGNETS PACK OF 4 CHILDHOOD MEMORY,MAGNETS PACK OF 4 HOME SWEET HOME,MAGNETS PACK OF 4 RETRO PHOTO,MAGNETS PACK OF 4 SWALLOWS,MAGNETS PACK OF 4 VINTAGE COLLAGE,MAGNETS PACK OF 4 VINTAGE LABELS,MAKE YOUR OWN FLOWERPOWER CARD KIT,MAKE YOUR OWN MONSOON CARD KIT,MAKE YOUR OWN PLAYTIME CARD KIT,MARIE ANTOINETTE TRINKET BOX GOLD,MARIE ANTOINETTE TRINKET BOX SILVER,MEASURING TAPE BABUSHKA BLUE,MEASURING TAPE BABUSHKA PINK,MEASURING TAPE BABUSHKA RED,MEDIUM PINK BUDDHA HEAD,MEMO BOARD COTTAGE DESIGN,MEMO BOARD RETROSPOT DESIGN,METAL DECORAT

## 5. Convert to a "bought / not bought" table

The Apriori algorithm doesn't care *how many* units were bought — only *whether* a product was part of the order or not. So we convert every value to `True`/`False`: any quantity greater than 0 becomes `True` (bought), and 0 stays `False` (not bought).

We do this by comparing the whole table to 0 at once (`basket > 0`), which pandas applies element-by-element automatically — this is simpler and faster than looping through cells with `applymap` (which is also deprecated in recent pandas versions).

In [23]:
basket_encoded = basket > 0

basket_encoded.head()

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,15CM CHRISTMAS GLASS BALL 20 LIGHTS,16 PIECE CUTLERY SET PANTRY DESIGN,18PC WOODEN CUTLERY SET DISPOSABLE,20 DOLLY PEGS RETROSPOT,200 RED + WHITE BENDY STRAWS,3 HOOK HANGER MAGIC GARDEN,3 PIECE SPACEBOY COOKIE CUTTER SET,3 RAFFIA RIBBONS 50'S CHRISTMAS,3 STRIPEY MICE FELTCRAFT,3 TIER CAKE TIN RED AND CREAM,3 TRADITIONAl BISCUIT CUTTERS SET,36 DOILIES DOLLY GIRL,36 DOILIES VINTAGE CHRISTMAS,36 FOIL HEART CAKE CASES,36 FOIL STAR CAKE CASES,36 PENCILS TUBE RED RETROSPOT,36 PENCILS TUBE SKULLS,36 PENCILS TUBE WOODLAND,3D HEARTS HONEYCOMB PAPER GARLAND,3D TRADITIONAL CHRISTMAS STICKERS,3D VINTAGE CHRISTMAS STICKERS,4 IVORY DINNER CANDLES SILVER FLOCK,4 PINK DINNER CANDLE SILVER FLOCK,4 TRADITIONAL SPINNING TOPS,5 HOOK HANGER MAGIC TOADSTOOL,5 HOOK HANGER RED MAGIC TOADSTOOL,6 GIFT TAGS 50'S CHRISTMAS,6 GIFT TAGS VINTAGE CHRISTMAS,6 RIBBONS EMPIRE,6 RIBBONS RUSTIC CHARM,6 ROCKET BALLOONS,60 CAKE CASES DOLLY GIRL DESIGN,60 CAKE CASES VINTAGE CHRISTMAS,60 TEATIME FAIRY CAKE CASES,6PC WOOD PLATE SET DISPOSABLE,72 SWEETHEART FAIRY CAKE CASES,A PRETTY THANK YOU CARD,ABC TREASURE BOOK BOX,ADULT APRON APPLE DELIGHT,ADVENT CALENDAR GINGHAM SACK,AGED GLASS SILVER T-LIGHT HOLDER,AIRLINE BAG VINTAGE JET SET BROWN,AIRLINE BAG VINTAGE JET SET RED,AIRLINE BAG VINTAGE JET SET WHITE,AIRLINE BAG VINTAGE TOKYO 78,AIRLINE BAG VINTAGE WORLD CHAMPION,"AIRLINE LOUNGE,METAL SIGN",ALARM CLOCK BAKELIKE CHOCOLATE,ALARM CLOCK BAKELIKE GREEN,ALARM CLOCK BAKELIKE IVORY,ALARM CLOCK BAKELIKE ORANGE,ALARM CLOCK BAKELIKE PINK,ALARM CLOCK BAKELIKE RED,ALPHABET HEARTS STICKER SHEET,ALUMINIUM STAMPED HEART,AMETHYST CHUNKY BEAD BRACELET W STR,ANGEL DECORATION STARS ON DRESS,ANTIQUE ALL GLASS CANDLESTICK,ANTIQUE GLASS DRESSING TABLE POT,ANTIQUE GLASS PEDESTAL BOWL,ANTIQUE SILVER BAUBLE LAMP,ANTIQUE SILVER T-LIGHT GLASS,ANTIQUE SILVER TEA GLASS ENGRAVED,APPLE BATH SPONGE,AREA PATROLLED METAL SIGN,ASS COLOUR GLOWING TIARAS,ASS FLORAL PRINT MULTI SCREWDRIVER,ASSORTED BOTTLE TOP MAGNETS,ASSORTED COLOUR BIRD ORNAMENT,ASSORTED COLOUR MINI CASES,ASSORTED COLOUR T-LIGHT HOLDER,ASSORTED COLOURS SILK FAN,ASSORTED EASTER DECORATIONS BELLS,ASSORTED EASTER GIFT TAGS,"ASSORTED FLOWER COLOUR ""LEIS""",ASSORTED TUTTI FRUTTI BRACELET,ASSORTED TUTTI FRUTTI MIRROR,ASSORTED TUTTI FRUTTI SMALL PURSE,ASSTD DESIGN 3D PAPER STICKERS,ASSTD DESIGN RACING CAR PEN,ASSTD FRUIT+FLOWERS FRIDGE MAGNETS,ASSTD RASTA KEY-CHAINS,BABUSHKA LIGHTS STRING OF 10,BAG 125g SWIRLY MARBLES,BAG 250g SWIRLY MARBLES,BAKING MOULD CHOCOLATE CUPCAKES,BAKING MOULD EASTER EGG MILK CHOC,BAKING MOULD EASTER EGG WHITE CHOC,BAKING MOULD HEART MILK CHOCOLATE,BAKING MOULD HEART WHITE CHOCOLATE,BAKING SET 9 PIECE RETROSPOT,BAKING SET SPACEBOY DESIGN,BALLOON ART MAKE YOUR OWN FLOWERS,BALLOON PUMP WITH 10 BALLOONS,BALLOON WATER BOMB PACK OF 35,BALLOONS WRITING SET,BANQUET BIRTHDAY CARD,BASKET OF TOADSTOOLS,BATH BUILDING BLOCK WORD,BEADED CRYSTAL HEART BLUE LARGE,BELLE JARDINIERE CUSHION COVER,BEWARE OF THE CAT METAL SIGN,BIG DOUGHNUT FRIDGE MAGNETS,BILI NUT AND WOOD NECKLACE,BINGO SET,BIRD DECORATION GREEN POLKADOT,BIRD DECORATION RED RETROSPOT,BIRD HOUSE HOT WATER BOTTLE,BIRDS MOBILE VINTAGE DESIGN,"BIRTHDAY CARD, RETRO SPOT",BISCUIT TIN 50'S CHRISTMAS,BISCUIT TIN VINTAGE CHRISTMAS,BISCUIT TIN VINTAGE GREEN,BISCUIT TIN VINTAGE RED,BLACK AND WHITE CAT BOWL,BLACK CANDELABRA T-LIGHT HOLDER,BLACK CHRISTMAS TREE 120CM,BLACK CHUNKY BEAD BRACELET W STRAP,BLACK ENAMEL FLOWER RING,BLACK KITCHEN SCALES,BLACK LOVE BIRD CANDLE,BLACK PIRATE TREASURE CHEST,BLACK RECORD COVER FRAME,BLACK/BLUE POLKADOT UMBRELLA,BLUE 3 PIECE POLKADOT CUTLERY SET,BLUE COAT RACK PARIS FASHION,BLUE DINER WALL CLOCK,BLUE DRAWER KNOB ACRYLIC EDWARDIAN,BLUE EGG SPOON,BLUE FLY SWAT,BLUE GEISHA GIRL,BLUE HAPPY BIRTHDAY BUNTING,BLUE HARMONICA IN BOX,BLUE OWL SOFT TOY,BLUE PAISLEY JOURNAL,BLUE PARTY BAGS,BLUE POLKADOT BEAKER,BLUE POLKADOT BOWL,BLUE POLKADOT COFFEE MUG,BLUE POLKADOT CUP,BLUE POLKADOT GARDEN PARASOL,BLUE POLKADOT KIDS BAG,BLUE POLKADOT PASSPORT COVER,BLUE POLKADOT PLATE,BLUE POLKADOT WRAP,BLUE REFECTORY CLOCK,BLUE ROSE FABRIC MIRROR,BLUE SCANDINAVIAN PAISLEY WRAP,BLUE SCOTTIE DOG W FLOWER PATTERN,BLUE STRIPE CERAMIC DRAWER KNOB,BLUE TEA TOWEL CLASSIC DESIGN,BLUE VINTAGE SPOT BEAKER,BOOM BOX SPEAKER BOYS,BOOM BOX SPEAKER GIRLS,BOTANICAL GARDENS WALL CLOCK,BOTANICAL LILY GREETING CARD,BOTTLE BAG RETROSPOT,BOX OF 24 COCKTAIL PARASOLS,BOX OF 6 CHRISTMAS CAKE DECORATIONS,BOX OF 6 MINI 50'S CRACKERS,BOX OF 6 MINI VINTAGE CRACKERS,BOX OF VINTAGE ALPHABET BLOCKS,BOX OF VINTAGE JIGSAW BLOCKS,BOYS VINTAGE TIN SEASIDE BUCKET,BREAD BIN DINER STYLE IVORY,BREAD BIN DINER STYLE PINK,BREAD BIN DINER STYLE RED,BRIGHT BLUES RIBBONS,BROCANTE SHELF WITH HOOKS,BROWN CHECK CAT DOORSTOP,BROWN KUKUI COCONUT SEED NECKLACE,BUFFALO BILL TREASURE BOOK BOX,BULL DOG BOTTLE TOP WALL CLOCK,BUNDLE OF 3 ALPHABET EXERCISE BOOKS,BUNDLE OF 3 RETRO NOTE BOOKS,BUNDLE OF 3 SCHOOL EXERCISE BOOKS,BUNNY WOODEN PAINTED WITH BIRD,BUTTERFLIES STICKERS,CABIN BAG VINTAGE RETROSPOT,CACTI T-LIGHT CANDLES,CAKE PLATE LOVEBIRD PINK,CAKE PLATE LOVEBIRD WHITE,CAKE STAND 3 TIER MAGIC GARDEN,CAKE STAND LOVEBIRD 2 TIER PINK,CAKE STAND WHITE TWO TIER LACE,CAKES AND BOWS GIFT TAPE,CAKES AND RABBITS DESIGN FLANNEL,CALENDAR PAPER CUT DESIGN,CAMOUFLAGE LED TORCH,CANDY SHOP STICKER SHEET,CANDY SPOT HAND BAG,CARAVAN SQUARE TISSUE BOX,CARD BILLBOARD FONT,CARD BIRTHDAY COWBOY,CARD CAT AND TREE,CARD CHRISTMAS VILLAGE,CARD CIRCUS PARADE,CARD DOLLY GIRL,CARD GINGHAM ROSE,CARD HOLDER GINGHAM HEART,CARD HOLDER LOVE BIRD SMALL,CARD I LOVE LONDON,CARD MOTORBIKE SANTA,CARD PARTY GAMES,CARD PSYCHEDELIC APPLES,CARD SUKI BIRTHDAY,CARD WEDDING DAY,CARDHOLDER GINGHAM CHRISTMAS TREE,CAROUSEL DESIGN WASHBAG,CARROT CHARLIE+LOLA COASTER SET,CARTOON PENCIL SHARPENERS,CAST IRON HOOK GARDEN TROWEL,CAT BOWL VINTAGE CREAM,CERAMIC BOWL WITH STRAWBERRY DESIGN,CERAMIC CHERRY CAKE MONEY BANK,CERAMIC HEART FAIRY CAKE MONEY BANK,CERAMIC PIRATE CHEST MONEY BANK,CERAMIC STRAWBERRY CAKE MONEY BANK,CERAMIC STRAWBERRY DESIGN MUG,CERAMIC STRAWBERRY MONEY BOX,CERAMIC STRAWBERRY TRINKET TRAY,CHARLIE & LOLA WASTEPAPER BIN FLORA,CHARLOTTE BAG APPLES DESIGN,CHARLOTTE BAG DOLLY GIRL DESIGN,CHARLOTTE BAG PINK POLKADOT,CHARLOTTE BAG SUKI DESIGN,CHARLOTTE BAG VINTAGE ALPHABET,CHERRY BLOSSOM DECORATIVE FLASK,CHERRY BLOSSOM DECORATIVE FLASK,CHERRY CROCHET FOOD COVER,CHERUB HEART DECORATION GOLD,CHEST OF DRAWERS GINGHAM HEART,CHICK GREY HOT WATER BOTTLE,CHILDREN'S APRON DOLLY GIRL,CHILDREN'S CIRCUS PARADE MUG,CHILDREN'S SPACEBOY MUG,CHILDRENS APRON APPLES DESIGN,CHILDRENS APRON SPACEBOY DESIGN,CHILDRENS CUTLERY CIRCUS PARADE,CHILDRENS CUTLERY DOLLY GIRL,CHILDRENS CUTLERY POLKADOT BLUE,CHILDRENS CUTLERY POLKADOT GREEN,CHILDRENS CUTLERY POLKADOT PINK,CHILDRENS CUTLERY RETROSPOT RED,CHILDRENS CUTLERY SPACEBOY,CHILDRENS DOLLY GIRL MUG,CHILDRENS GARDEN GLOVES BLUE,CHILDRENS GARDEN GLOVES PINK,CHILDRENS TOY COOKING UTENSIL SET,CHILDS BREAKFAST SET CIRCUS PARADE,CHILDS BREAKFAST SET DOLLY GIRL,CHILDS BREAKFAST SET SPACEBOY,CHILDS GARDEN BRUSH BLUE,CHILDS GARDEN BRUSH PINK,CHILDS GARDEN FORK BLUE,CHILDS GARDEN FORK PINK,CHILDS GARDEN RAKE BLUE,CHILDS GARDEN RAKE PINK,CHILDS GARDEN SPADE BLUE,CHILDS GARDEN SPADE PINK,CHILDS GARDEN TROWEL BLUE,CHILDS GARDEN TROWEL PINK,CHINESE DRAGON PAPER LANTERNS,CHOCOLATE BOX RIBBONS,CHOCOLATE CALCULATOR,CHOCOLATE HOT WATER BOTTLE,CHOCOLATE THIS WAY METAL SIGN,CHRISTMAS CARD SCREEN PRINT,CHRISTMAS CARD STACK OF PRESENTS,CHRISTMAS CRAFT LITTLE FRIENDS,CHRISTMAS CRAFT TREE TOP ANGEL,CHRISTMAS CRAFT WHITE FAIRY,CHRISTMAS GINGHAM STAR,CHRISTMAS GINGHAM TREE,CHRISTMAS HANGING SNOWFLAKE,CHRISTMAS LIGHTS 10 REINDEER,CHRISTMAS LIGHTS 10 SANTAS,CHRISTMAS LIGHTS 10 VINTAGE BAUBLES,CHRISTMAS METAL POSTCARD WITH BELLS,CHRISTMAS METAL TAGS ASSORTED,CHRISTMAS PUDDING TRINKET POT,CHRISTMAS RETROSPOT ANGEL WOOD,CHRISTMAS RETROSPOT TREE WOOD,CHRISTMAS STAR WISH LIST CHALKBOARD,CHRISTMAS TOILET ROLL,CHRISTMAS TREE HANGING GOLD,CHRISTMAS TREE PAINTED ZINC,CHRYSANTHEMUM NOTEBOOK,CINAMMON & ORANGE WREATH,CINNAMON SCENTED VOTIVE CANDLE,CIRCUS PARADE BABY GIFT SET,CIRCUS PARADE CHILDRENS EGG CUP,CIRCUS PARADE LUNCH BOX,CLASSIC CAFE SUGAR DISPENSER,CLASSIC CHROME BICYCLE BELL,CLASSIC GLASS COOKIE JAR,CLASSIC METAL BIRDCAGE PLANT HOLDER,CLASSICAL ROSE SMALL VASE,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,CLOTHES PEGS RETROSPOT PACK 24,COCKTAIL SWORDS 50 PIECES,COFFEE MUG APPLES DESIGN,COFFEE MUG CAT + BIRD DESIGN,COFFEE MUG DOG + BALL DESIGN,COFFEE MUG PEARS DESIGN,COFFEE MUG PINK PAISLEY DESIGN,COLOURING PENCILS BROWN TUBE,COOK WITH WINE METAL SIGN,CORDIAL GLASS JUG,COSY HOUR CIGAR BOX MATCHES,COSY SLIPPER SHOES SMALL GREEN,COTTON APRON PANTRY DESIGN,COWBOYS AND INDIANS BIRTHDAY CARD,CREAM FELT EASTER EGG BASKET,CREAM HEART CARD HOLDER,CREAM SWEETHEART EGG HOLDER,CREAM SWEETHEART MINI CHEST,CROCHET ROSE PURSE WITH SUEDE BACK,CUPCAKE LACE PAPER SET 6,CURIOUS IMAGES GIFT WRAP SET,CUTE CATS TAPE,DAIRY MAID STRIPE MUG,DAIRY MAID TRADITIONAL TEAPOT,DAISIES HONEYCOMB GARLAND,DANISH ROSE DECORATIVE PLATE,DANISH ROSE DELUXE COASTER,DANISH ROSE ROUND SEWING BOX,DANISH ROSE TRINKET TRAYS,DECORATIVE CATS BATHROOM BOTTLE,DECORATIVE WICKER HEART LARGE,DELUXE SEWING KIT,DINOSAUR HEIGHT CHART STICKER SET,DINOSAUR KEYRINGS ASSORTED,DINOSAUR LUNCH BOX WITH CUTLERY,DINOSAUR PARTY BAG + STICKER SET,DINOSAURS WRITING SET,DISCO BALL CHRISTMAS DECORATION,DO NOT TOUCH MY STUFF DOOR HANGER,DOCTOR'S BAG SOFT TOY,DOG BOWL CHASING BALL DESIGN,DOG BOWL VINTAGE CREAM,DOGGY RUBBER,DOILEY STORAGE TIN,DOILY THANK YOU CARD,DOLLY GIRL BABY GIFT SET,DOLLY GIRL CHILDRENS BOWL,DOLLY GIRL CHILDRENS CUP,DOLLY GIRL CHILDRENS EGG CUP,DOLLY GIRL LUNCH BOX,DOLLY GIRL MINI BACKPACK,DOLLY HONEYCOMB GARLAND,DOLLY MIXTURE CHILDREN'S UMBRELLA,DOOR HANGER MUM + DADS ROOM,DOORMAT 3 SMILEY CATS,DOORMAT AIRMAIL,DOORMAT BLACK FLOCK,DOORMAT ENGLISH ROSE,DOORMAT FAIRY CAKE,DOORMAT FANCY FONT HOME SWEET HOME,DOORMAT HEARTS,DOORMAT HOME SWEET HOME BLUE,DOORMAT I LOVE LONDON,DOORMAT KEEP CALM AND COME IN,DOORMAT MERRY CHRISTMAS RED,DOORMAT NEIGHBOURHOOD WITCH,DOORMAT NEW ENGLAND,DOORMAT PEACE ON EARTH BLUE,DOORMAT RED RETROSPOT,DOORMAT RESPECTABLE HOUSE,DOORMAT SPOTTY HOME SWEET HOME,DOORMAT UNION FLAG,DOORMAT UNION JACK GUNS AND ROSES,DOORMAT VINTAGE LEAF,DOORMAT WELCOME TO OUR HOME,DOORSTOP RETROSPOT HEART,DOUGHNUT LIP GLOSS,DRAWER KNOB CERAMIC IVORY,DRAWER KNOB CERAMIC RED,DRAWER KNOB CRACKLE GLAZE BLUE,DRAWER KNOB CRACKLE GLAZE GREEN,DRAWER KNOB CRACKLE GLAZE PINK,DRAWER KNOB VINTAGE GLASS BALL,DRAWER KNOB VINTAGE GLASS HEXAGON,DRAWER KNOB VINTAGE GLASS STAR,EASTER TIN BUNNY BOUQUET,EASTER TIN CHICKS IN GARDEN,EASTER TIN CHICKS PINK DAISY,EASTER TIN KEEPSAKE,EDWARDIAN PARASOL BLACK,EDWARDIAN PARASOL NATURAL,EDWARDIAN PARASOL PINK,EDWARDIAN PARASOL RED,EGG CUP MILKMAID HEIDI,EGG CUP MILKMAID HELGA,EGG CUP MILKMAID INGRID,EGG CUP NATURAL CHICKEN,EGG FRYING PAN RED,EIGHT PIECE SNAKE SET,"ELEPHANT, BIRTHDAY CARD,",EMBROIDERED RIBBON REEL DAISY,EMBROIDERED RIBBON REEL EMILY,EMBROIDERED RIBBON REEL REBECCA,EMBROIDERED RIBBON REEL ROSIE,EMBROIDERED RIBBON REEL SALLY,EMBROIDERED RIBBON REEL SUSIE,EMPIRE BIRTHDAY CARD,EMPIRE TISSUE BOX,ENAMEL BLUE RIM COFFEE CONTAINER,ENAMEL COLANDER CREAM,ENAMEL FLOWER JUG CREAM,ENAMEL PINK COFFEE CONTAINER,ENAMEL PINK TEA CONTAINER,ENCHANTED BIRD COATHANGER 5 HOOK,ENGLISH ROSE GARDEN SECATEURS,ENGLISH ROSE HOT WATER BOTTLE,ENGLISH ROSE NOTEBOOK A7 SIZE,ENGLISH ROSE SMALL SCENTED FLOWER,ETCHED GLASS COASTER,FAIRY CAKE BIRTHDAY CANDLE SET,FAIRY CAKE FLANNEL ASSORTED COLOUR,FAIRY CAKES NOTEBOOK A6 SIZE,FAIRY CAKES NOTEBOOK A7 SIZE,FAIRY TALE COTTAGE NIGHT LIGHT,FAIRY TALE COTTAGE NIGHTLIGHT,FAMILY PHOTO FRAME CORNICE,"FANCY FONT BIRTHDAY CARD,",FANCY FONTS BIRTHDAY WRAP,FAWN BLUE HOT WATER BOTTLE,"FEATHER PEN,LIGHT PINK",FELT EGG COSY CHICKEN,FELT FARM ANIMAL WHITE BUNNY,FELT TOADSTOOL SMALL,FELT TOADSTOOL LARGE,FELTCRAFT 6 FLOWER FRIENDS,FELTCRAFT BOY JEAN-PAUL KIT,FELTCRAFT CHRISTMAS FAIRY,FELTCRAFT CUSHION BUTTERFLY,FELTCRAFT CUSHION OWL,FELTCRAFT CUSHION RABBIT,FELTCRAFT DOLL EMILY,FELTCRAFT DOLL MARIA,FELTCRAFT DOLL MOLLY,FELTCRAFT DOLL ROSIE,FELTCRAFT GIRL AMELIE KIT,FELTCRAFT HAIRBAND PINK AND BLUE,FELTCRAFT HAIRBANDS PINK AND WHITE,FELTCRAFT PRINCESS CHARLOTTE DOLL,FELTCRAFT PRINCESS LOLA DOLL,FELTCRAFT PRINCESS OLIVIA DOLL,FIRST CLASS PASSPORT COVER,FIVE HEART HANGING DECORATION,FLOWER VINE RAFFIA FOOD COVER,FLOWERS TILE HOOK,FLUTED ANTIQUE CANDLE HOLDER,FLYING PIG WATERING CAN,FOLDING BUTTERFLY MIRROR HOT PINK,FOLDING BUTTERFLY MIRROR IVORY,FOLDING BUTTERFLY MIRROR RED,FOLDING UMBRELLA BLACKBLUE POLKADOT,FOLDING UMBRELLA CHOCOLATE POLKADOT,FOLDING UMBRELLA CREAM POLKADOT,FOLDING UMBRELLA PINKWHITE POLKADOT,FOLDING UMBRELLA RED/WHITE POLKADOT,FOLDING UMBRELLA WHITE/RED POLKADOT,FOLKART STAR CHRISTMAS DECORATIONS,FOOD CONTAINER SET 3 LOVE HEART,FOOD/DRINK SPONGE STICKERS,FOOT STOOL HOME SWEET HOME,FRENCH ENAMEL CANDLEHOLDER,FRENCH ENAMEL WATER BASIN,FRENCH STYLE STORAGE JAR BONBONS,FRIDGE MAGNETS LA VIE EN ROSE,FRIDGE MAGNETS LES ENFANTS ASSORTED,FRIDGE MAGNETS US DINER ASSORTED,FRYING PAN PINK POLKADOT,FRYING PAN RED RETROSPOT,FRYING PAN UNION FLAG,FULL ENGLISH BREAKFAST PLATE,FUNKY DIVA PEN,FUNKY WASHING UP GLOVES ASSORTED,GARDENERS KNEELING PAD CUP OF TEA,GARDENERS KNEELING PAD KEEP CALM,GARLAND WITH HEARTS AND BELLS,GARLAND WITH STARS AND BELLS,GIANT 50'S CHRISTMAS CRACKER,GIFT BAG BIRTHDAY,GIFT BAG PSYCHEDELIC APPLES,GIN & TONIC DIET GREETING CARD,GIN + TONIC DIET METAL SIGN,GINGERBREAD MAN COOKIE CUTTER,GINGHAM HEART DOORSTOP RED,GINGHAM HEART DECORATION,GINGHAM RECIPE BOOK BOX,GIRAFFE WOODEN RULER,GIRLS VINTAGE TIN SEASIDE BUCKET,GLAMOROUS MUG,GLASS BEURRE DISH,GLASS SONGBIRD STORAGE JAR,GLASS BONNE JAM JAR,GLASS CLOCHE SMALL,GLASS JAR DAISY FRESH COTTON WOOL,GLASS JAR PEACOCK BATH SALTS,GLITTER CHRISTMAS STAR,GLITTER HEART DECORATION,GLITTER STAR GARLAND WITH BELLS,GRAND CHOCOLATECANDLE,GREEN 3 PIECE POLKADOT CUTLERY SET,GREEN BIRDHOUSE DECORATION,GREEN CHRISTMAS TREE STRING 20LIGHT,GREEN GEISHA GIRL,GREEN GIANT GARDEN THERMOMETER,GREEN METAL BOX ARMY SUPPLIES,GREEN POLKADOT BOWL,GREEN POLKADOT PLATE,GREEN REGENCY TEACUP AND SAUCER,GREEN VINTAGE SPOT BEAKER,"GREETING CARD, OVERCROWDED POOL.",GREY FLORAL FELTCRAFT SHOULDER BAG,GREY HEART HOT WATER BOTTLE,GROW A FLYTRAP OR SUNFLOWER IN TIN,GROW YOUR OWN HERBS SET OF 3,GROW YOUR OWN PLANT IN A CAN,GUMBALL COAT RACK,GUMBALL MAGAZINE RACK,GYMKHANA TREASURE BOOK BOX,HAIRCLIPS FORTIES FABRIC ASSORTED,HAND WARMER BABUSHKA DESIGN,HAND WARMER BIRD DESIGN,HAND WARMER RED LOVE HEART,HAND WARMER RED RETROSPOT,HAND WARMER SCOTTY DOG DESIGN,HAND WARMER UNION JACK,HANGING BUTTERFLY T-LIGHT HOLDER,HANGING HEART BONHEUR,HANGING HEART JAR T-LIGHT HOLDER,HANGING HEART ZINC T-LIGHT HOLDER,HANGING HEN ON NEST DECORATION,HANGING MINI COLOURED BOTTLES,HANGING QUILTED PATCHWORK APPLES,HANGING SPRING FLOWER EGG SMALL,HAPPY STENCIL CRAFT,HEADS AND TAILS SPORTING FUN,HEART FILIGREE DOVE SMALL,HEART FILIGREE DOVE LARGE,HEART MINI PORTRAIT FRAME,HEART OF WICKER SMALL,HEART SHAPED HOLLY WREATH,HEART T-LIGHT HOLDER WILLIE WINKIE,HEART WOODEN CHRISTMAS DECORATION,HEART WREATH DECORATION WITH BELL,HEARTS STICKERS,HEN HOUSE W CHICK STANDING,HENRIETTA HEN MUG,HI TEC ALPINE HAND WARMER,HOLIDAY FUN LUDO,HOME BUILDING BLOCK WORD,HOME SWEET HOME CUSHION COVER,HOME SWEET HOME HOOK,HOME SWEET HOME METAL SIGN,HOME SWEET HOME MUG,HOMEMADE JAM SCENTED CANDLES,HOT BATHS METAL SIGN,HOT WATER BOTTLE BABUSHKA,HOT WATER BOTTLE KEEP CALM,HOT WATER BOTTLE TEA AND SYMPATHY,HOUSE SHAPE PENCIL SHARPENER,HYACINTH BULB T-LIGHT CANDLES,I LOVE LONDON BABY GIFT SET,I LOVE LONDON BEAKER,I'M ON HOLIDAY METAL SIGN,ICE CREAM BUBBLES,ICE CREAM DESIGN GARDEN PARASOL,ICE CREAM PEN LIP GLOSS,ICE CREAM SUNDAE LIP GLOSS,ICON MUG REVOLUTIONARY,ILLUSTRATED CAT BOWL,INFLATABLE POLITICAL GLOBE,IVORY DINER WALL CLOCK,IVORY GIANT GARDEN THERMOMETER,IVORY HANGING DECORATION HEART,IVORY KITCHEN SCALES,IVORY PILLAR CANDLE GOLD FLOCK,IVORY PILLAR CANDLE SILVER FLOCK,IVORY WICKER HEART LARGE,IVORY WICKER HEART MEDIUM,IVORY WICKER HEART SMALL,JAM CLOCK MAGNET,JAM JAR WITH GREEN LID,JAM JAR WITH PINK LID,JAM MAKING SET PRINTED,JAM MAKING SET WITH JARS,JAZZ HEARTS ADDRESS BOOK,JAZZ HEARTS PURSE NOTEBOOK,JIGSAW TOADSTOOLS 3 PIECE,JIGSAW TREE WITH BIRDHOUSE,JINGLE BELL HEART ANTIQUE GOLD,JINGLE BELL HEART DECORATION,JOY WOODEN BLOCK LETTERS,JUMBO BAG BAROQUE BLACK WHITE,JUMBO BAG 50'S CHRISTMAS,JUMBO BAG ALPHABET,JUMBO BAG APPLES,JUMBO BAG DOILEY PATTERNS,JUMBO BAG DOLLY GIRL DESIGN,JUMBO BAG OWLS,JUMBO BAG PEARS,JUMBO BAG PINK POLKADOT,JUMBO BAG PINK VINTAGE PAISLEY,JUMBO BAG RED RETROSPOT,JUMBO BAG SCANDINAVIAN BLUE PAISLEY,JUMBO BAG SPACEBOY DESIGN,JUMBO BAG STRAWBERRY,JUMBO BAG TOYS,JUMBO BAG VINTAGE CHRISTMAS,JUMBO BAG VINTAGE DOILY,JUMBO BAG VINTAGE LEAF,JUMBO BAG WOODLAND ANIMALS,JUMBO SHOPPER VINTAGE RED PAISLEY,JUMBO STORAGE BAG SKULLS,JUMBO STORAGE BAG SUKI,JUNGLE POPSICLES ICE LOLLY HOLDERS,JUNGLE POPSICLES ICE LOLLY MOULDS,KEEP OUT BOYS DOOR HANGER,"KEY FOB , BACK DOOR","KEY FOB , SHED",KEY RING BASEBALL BOOT ASSORTED,KEY RING BASEBALL BOOT UNION JACK,KINGS CHOICE BISCUIT TIN,KINGS CHOICE MUG,KINGS CHOICE TEA CADDY,KITTY PENCIL ERASERS,KNICKERBOCKERGLORY MAGNET ASSORTED,KNITTED UNION FLAG HOT WATER BOTTLE,LA JARDIN BOTANIQUE CUSHION COVER,LA PALMIERA TILE HOOK,LADIES & GENTLEMEN METAL SIGN,LADYBIRD + BEE RAFFIA FOOD COVER,LANDMARK FRAME COVENT GARDEN,LANDMARK FRAME NOTTING HILL,LANDMARK FRAME OXFORD STREET,LANTERN CREAM GAZEBO,LARGE BONNE JAM JAR T-LIGHT HOLDER,LARGE CAKE TOWEL PINK SPOTS,LARGE CAMPHOR WOOD FIELD MUSHROOM,LARGE DECO JEWELLERY STAND,LARGE HANGING IVORY & RED WOOD BIRD,LARGE HEART MEASURING SPOONS,LARGE IVORY HEART WALL ORGANISER,LARGE POPCORN HOLDER,LARGE PURPLE BABUSHKA NOTEBOOK,LARGE RED BABUSHKA NOTEBOOK,LARGE RED RETROSPOT WINDMILL,LARGE WHITE HEART OF WICKER,LARGE YELLOW BABUSHKA NOTEBOOK,LAUREL HEART ANTIQUE GOLD,LAUREL STAR ANTIQUE SILVER,LAVENDER SCENTED FABRIC HEART,LE JARDIN BOTANIQUE CUSHION COVER,LED TEA LIGHTS,LETS GO SHOPPING COTTON TOTE BAG,LIPSTICK PEN RED,LOLITA DESIGN COTTON TOTE BAG,LONDON BUS COFFEE MUG,LOVE BUILDING BLOCK WORD,LOVE GARLAND PAINTED ZINC,LOVE HEART SOCK HANGER,LOVE HOT WATER BOTTLE,LOVE LARGE WOOD LETTERS,LOVEBIRD HANGING DECORATION WHITE,LOVELY BONBON STICKER SHEET,LUNCH BAG BLACK SKULL.,LUNCH BAG ALPHABET DESIGN,LUNCH BAG APPLE DESIGN,LUNCH BAG CARS BLUE,LUNCH BAG DOILEY PATTERN,LUNCH BAG DOLLY GIRL DESIGN,LUNCH BAG PAISLEY PARK,LUNCH BAG PINK POLKADOT,LUNCH BAG RED RETROSPOT,LUNCH BAG RED VINTAGE DOILY,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG VINTAGE DOILY,LUNCH BAG VINTAGE LEAF DESIGN,LUNCH BAG WOODLAND,LUNCH BOX I LOVE LONDON,LUNCH BOX WITH CUTLERY RETROSPOT,MAGIC DRAWING SLATE BUNNIES,MAGIC DRAWING SLATE CIRCUS PARADE,MAGIC DRAWING SLATE DINOSAUR,MAGIC DRAWING SLATE DOLLY GIRL,MAGIC DRAWING SLATE GO TO THE FAIR,MAGIC DRAWING SLATE LEAP FROG,MAGIC DRAWING SLATE SPACEBOY,MAGIC SHEEP WOOL GROWING FROM PAPER,MAGNETS PACK OF 4 CHILDHOOD MEMORY,MAGNETS PACK OF 4 HOME SWEET HOME,MAGNETS PACK OF 4 RETRO PHOTO,MAGNETS PACK OF 4 SWALLOWS,MAGNETS PACK OF 4 VINTAGE COLLAGE,MAGNETS PACK OF 4 VINTAGE LABELS,MAKE YOUR OWN FLOWERPOWER CARD KIT,MAKE YOUR OWN MONSOON CARD KIT,MAKE YOUR OWN PLAYTIME CARD KIT,MARIE ANTOINETTE TRINKET BOX GOLD,MARIE ANTOINETTE TRINKET BOX SILVER,MEASURING TAPE BABUSHKA BLUE,MEASURING TAPE BABUSHKA PINK,MEASURING TAPE BABUSHKA RED,MEDIUM PINK BUDDHA HEAD,MEMO BOARD COTTAGE DESIGN,MEMO BOARD RETROSPOT DESIGN,METAL DECORAT

## 6. Find frequent itemsets with Apriori

The Apriori algorithm scans the basket table and finds combinations of products that appear together often enough to be meaningful. "Often enough" is controlled by `min_support`:

**Support** = (number of invoices containing this itemset) / (total number of invoices)

For example, `support = 0.05` means the itemset appears in at least 5% of all invoices. We start with a fairly low threshold (there are many products and each individual one is rare) and can raise it later if we get too many results to review.

In [24]:
frequent_itemsets = apriori(basket_encoded, min_support=0.05, use_colnames=True)

# Add a column with the number of products in each itemset, useful for filtering later
frequent_itemsets['itemset_length'] = frequent_itemsets['itemsets'].apply(len)

print(f'Found {len(frequent_itemsets)} frequent itemsets')
frequent_itemsets.sort_values('support', ascending=False).head(10)

Found 127 frequent itemsets

     support                                          itemsets  itemset_length
49  0.192612                   frozenset({RABBIT NIGHT LIGHT})               1
57  0.184697        frozenset({RED TOADSTOOL LED NIGHT LIGHT})               1
47  0.176781     frozenset({PLASTERS IN TIN WOODLAND ANIMALS})               1
43  0.174142       frozenset({PLASTERS IN TIN CIRCUS PARADE })               1
64  0.163588  frozenset({ROUND SNACK BOXES SET OF4 WOODLAND })               1
27  0.158311              frozenset({LUNCH BAG RED RETROSPOT})               1
33  0.147757    frozenset({LUNCH BOX WITH CUTLERY RETROSPOT })               1
71  0.142480          frozenset({SET/6 RED SPOTTY PAPER CUPS})               1
55  0.142480             frozenset({RED RETROSPOT MINI CASES})               1
45  0.139842             frozenset({PLASTERS IN TIN SPACEBOY})               1

## 7. Generate association rules

A frequent itemset just says "these products often appear together" — it doesn't say which one predicts the other. **Association rules** turn itemsets into "if a customer buys A, they are likely to also buy B" statements, with three key metrics:

- **Support**: how often A and B appear together, out of all invoices (as above)
- **Confidence**: out of the invoices that contain A, what fraction also contain B — i.e. `P(B | A)`
- **Lift**: how much more likely B is to be bought when A is bought, compared to B's normal popularity on its own. `lift = 1` means no relationship, `lift > 1` means a positive relationship (they're bought together more than random chance would suggest), `lift < 1` means a negative relationship

In [25]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1.0)

# Sort by lift descending to see the strongest relationships first
rules = rules.sort_values('lift', ascending=False)

print(f'Found {len(rules)} rules')
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

Found 100 rules

,antecedents,consequents,support,confidence,lift
49,frozenset({PACK OF 6 SKULL PAPER PLATES}),frozenset({PACK OF 6 SKULL PAPER CUPS}),0.052770,0.909091,13.781818
48,frozenset({PACK OF 6 SKULL PAPER CUPS}),frozenset({PACK OF 6 SKULL PAPER PLATES}),0.052770,0.800000,13.781818
14,frozenset({CHILDRENS CUTLERY DOLLY GIRL }),frozenset({CHILDRENS CUTLERY SPACEBOY }),0.065963,0.892857,12.533069
15,frozenset({CHILDRENS CUTLERY SPACEBOY }),frozenset({CHILDRENS CUTLERY DOLLY GIRL }),0.065963,0.925926,12.533069
82,"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",frozenset({ALARM CLOCK BAKELIKE RED }),0.065963,0.862069,8.830382
87,frozenset({ALARM CLOCK BAKELIKE RED }),"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",0.065963,0.675676,8.830382
85,frozenset({ALARM CLOCK BAKELIKE GREEN}),"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",0.065963,0.657895,8.598004
84,"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",frozenset({ALARM CLOCK BAKELIKE GREEN}),0.065963,0.862069,8.598004
3,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.081794,0.837838,8.356330
2,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE RED }),0.081794,0.815789,8.356330

## 8. Interpret the top rules

`antecedents` = the product(s) already in the basket (the "if"). `consequents` = the product(s) likely to be added (the "then").

Read a row like: *antecedents = {Product A}, consequents = {Product B}, confidence = 0.75, lift = 6.2* as:

> "75% of customers who buy Product A also buy Product B — and they're about 6.2x more likely to do so than a random customer."

This is exactly the kind of insight that powers "frequently bought together" recommendations and cross-selling decisions.

In [26]:
# Filter to rules with strong confidence AND strong lift, for the clearest, most actionable relationships
strong_rules = rules[(rules['confidence'] >= 0.5) & (rules['lift'] >= 3)]

print(f'Strong rules (confidence >= 0.5 and lift >= 3): {len(strong_rules)}')
strong_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(15)

Strong rules (confidence >= 0.5 and lift >= 3): 53

,antecedents,consequents,support,confidence,lift
49,frozenset({PACK OF 6 SKULL PAPER PLATES}),frozenset({PACK OF 6 SKULL PAPER CUPS}),0.052770,0.909091,13.781818
48,frozenset({PACK OF 6 SKULL PAPER CUPS}),frozenset({PACK OF 6 SKULL PAPER PLATES}),0.052770,0.800000,13.781818
14,frozenset({CHILDRENS CUTLERY DOLLY GIRL }),frozenset({CHILDRENS CUTLERY SPACEBOY }),0.065963,0.892857,12.533069
15,frozenset({CHILDRENS CUTLERY SPACEBOY }),frozenset({CHILDRENS CUTLERY DOLLY GIRL }),0.065963,0.925926,12.533069
82,"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",frozenset({ALARM CLOCK BAKELIKE RED }),0.065963,0.862069,8.830382
87,frozenset({ALARM CLOCK BAKELIKE RED }),"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",0.065963,0.675676,8.830382
85,frozenset({ALARM CLOCK BAKELIKE GREEN}),"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",0.065963,0.657895,8.598004
84,"frozenset({ALARM CLOCK BAKELIKE PINK, ALARM CL...",frozenset({ALARM CLOCK BAKELIKE GREEN}),0.065963,0.862069,8.598004
3,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.081794,0.837838,8.356330
2,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE RED }),0.081794,0.815789,8.356330
86,frozenset({ALARM CLOCK BAKELIKE PINK}),"frozenset({ALARM CLOCK BAKELIKE RED , ALARM CL...",0.065963,0.625000,7.641129
83,"frozenset({ALARM CLOCK BAKELIKE RED , ALARM CL...",frozenset({ALARM CLOCK BAKELIKE PINK}),0.065963,0.806452,7.641129
7,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE PINK}),0.076517,0.783784,7.426351
6,frozenset({ALARM CLOCK BAKELIKE PINK}),frozenset({ALARM CLOCK BAKELIKE RED }),0.076517,0.725000,7.426351
95,"frozenset({SET/6 RED SPOTTY PAPER CUPS, SET/20...",frozenset({SET/6 RED SPOTTY PAPER PLATES}),0.102902,0.975000,7.390500

## 9. Save the rules

In [27]:
OUTPUT_PATH = Path('..') / 'data' / 'processed' / f'association_rules_{COUNTRY.lower()}.csv'

# frozenset objects (antecedents/consequents) need to be converted to plain text before saving to CSV
rules_to_save = rules.copy()
rules_to_save['antecedents'] = rules_to_save['antecedents'].apply(lambda x: ', '.join(sorted(x)))
rules_to_save['consequents'] = rules_to_save['consequents'].apply(lambda x: ', '.join(sorted(x)))

rules_to_save.to_csv(OUTPUT_PATH, index=False)
print(f'Saved {len(rules_to_save)} rules to: {OUTPUT_PATH.resolve()}')

Saved 100 rules to: D:\New folder\BasketIQ\data\processed\association_rules_france.csv

## 10. Optional: try another country

Once this works, you can go back to Section 3, change `COUNTRY` to another market with enough transactions (e.g. `'Germany'`), and re-run the notebook to compare shopping patterns across markets.